### ISSUE TITLE
Not compatible with Symfony v6.1.3?

### ISSUE THREAD

**Issue by JainJayan** [m2mtech/weblate-translation-provider#1]
After following the installation guide with a Symfony 6.1 project, I seem to be getting an error from the config. My config is

```yaml
framework:
    translator:
        providers:
            weblate:
                dsn: '%env(WEBLATE_DSN)%'
                locales: ['en', 'de']
```

When calling `bin/console translation:push` the following error is printed:

> The "weblate" scheme is not supported.

Is there perhaps an incompatibility with Symfony 6.1?
