### ISSUE TITLE
Documentation: How to set source-language other than English

### ISSUE THREAD

**Issue by tobias47n9e** [m2mtech/weblate-translation-provider#2]
When pushing translations to a new project using this config:

```yaml
framework:
    default_locale: '%locale%'
    translator:
        providers:
            weblate:
                dsn: '%env(WEBLATE_DSN)%'
                locales: ['de', 'fr', 'it']
```

and in `services.yaml`:

```yaml
parameters:
    locale: 'de'
```

and in my `translations` folder I have 3 files:

```
messages.de.yml
messages.fr.yml
messages.it.yml
```

and this command:

```
bin/console translation:push --domains=messages weblate
```

I get this result (after starting a translation project for Italian):

![image](https://user-images.githubusercontent.com/6953323/185346324-ee27e331-dd8b-4d01-be22-a5e0d1d691a5.png)

Would it be possible to document how to push e.g. "de" as the source-language? Sorry if this falls under support, rather than bug report.

**Comment by m2mtech** [comment]
Sorry, for the stupid answer: It works for me ;)

The bundle uses `kernel.default_locale`
https://github.com/m2mtech/weblate-translation-provider/blob/3af95203448161f774a4d48cf0c835c779c6466c/src/Resources/config/services.php#L20-L29

and provides it to weblate when creating a component:
https://github.com/m2mtech/weblate-translation-provider/blob/3af95203448161f774a4d48cf0c835c779c6466c/src/Api/ComponentApi.php#L136-L144

My settings in symfony are:

```yml
framework:
    default_locale: de
    translator:
        fallbacks:
            - de
        providers:
            weblate:
                dsn: '%env(WEBLATE_DSN)%'
                locales: [en, de]
```

Please try to figure out, if the bundle uses the correct `default_locale` or if weblate ignores the provided source language.
